class Tickers(object):
    
    tickers = {
        'DOW': [
            'AXP',
            'BA',
            'CAT',
            'CSCO',
            'CVX',
            'DD',
            'DIS',
            'GE',
            'GS',
            'HD',
            'IBM',
            'INTC',
            'JNJ',
            'JPM',
            'KO',
            'MCD',
            'MMM',
            'MRK',
            'MSFT',
            'NKE',
            'PFE',
            'PG',
            'T',
            'TRV',
            'UNH',
            'UTX',
            'V',
            'VZ',
            'WMT',
            'XOM',
        ],
    }